version: "3.6"

services:
  chia:
    image: ghcr.io/chia-network/chia:latest
    container_name: chia
    restart: unless-stopped
    environment:
      - keys=persistent
      - TZ=Europe/Madrid
      - log_level=INFO
      - log_to_file=true
    volumes:
      - ./.chia:/root/.chia
      - ./.chia_keys:/root/.chia_keys
      - ./disks:/disks
      - ./scripts/chia--add-nodes.sh:/scripts/chia--add-nodes.sh
    ports:
      - "8444:8444"
      - "55400:55400"

  chiadog:
    build:
      context: https://github.com/martomi/chiadog.git#main
    container_name: chiadog
    restart: unless-stopped
    volumes:
      - ./.chiadog:/root/.chiadog
      - ./.chia/mainnet/log:/root/.chia/mainnet/log:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /run/udev:/run/udev:ro
      - ./.scrutiny/influxdb:/opt/scrutiny/influxdb
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin

  proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_socket_proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: chia
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    environment:
      - DOCKER_HOST=proxy:2375
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
    security_opt:
      - apparmor=unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    ports:
      - "82:19999"

  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: on-failure
    environment:
      - TZ=Europe/Madrid
      - USERID=1000
      - GROUPID=1000
    command: '-s "chia-fd-x;/chia-fd-x;yes;no;no;chia" -u "chia;chia" -G "chia-fd-x;create mask = 0755" -G "chia-fd-x;force create mode = 0755" -r -p'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
